config/routes.rb
Mark6::Application.routes.draw do
  resources :line_items

  resources :bins

  get "library/index"
  resources :certifications
  

  
  root 'library#index'

end

app/models/bin.rb
class Bin < ActiveRecord::Base
	has_many :line_items, dependent: :destroy
end

app/models/certification.rb
class Certification < ActiveRecord::Base
	validates :cert_name, :cert_company, :category, :description, :logo_url, presence: true
	validates :cert_name, uniqueness: true
	has_many :line_items

	before_destroy :ensure_not_referenced_by_any_line_item

	private

	def ensure_not_referenced_by_any_line_item
		if line_items.empty?
			return true
		else
			errors.add(:base, 'Line Items present')
			return false
		end
	end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :certification
  belongs_to :bin
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bins_controller.rb
class BinsController < ApplicationController
  before_action :set_bin, only: [:show, :edit, :update, :destroy]

  # GET /bins
  # GET /bins.json
  def index
    @bins = Bin.all
  end

  # GET /bins/1
  # GET /bins/1.json
  def show
  end

  # GET /bins/new
  def new
    @bin = Bin.new
  end

  # GET /bins/1/edit
  def edit
  end

  # POST /bins
  # POST /bins.json
  def create
    @bin = Bin.new(bin_params)

    respond_to do |format|
      if @bin.save
        format.html { redirect_to @bin, notice: 'Bin was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bin }
      else
        format.html { render action: 'new' }
        format.json { render json: @bin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bins/1
  # PATCH/PUT /bins/1.json
  def update
    respond_to do |format|
      if @bin.update(bin_params)
        format.html { redirect_to @bin, notice: 'Bin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bins/1
  # DELETE /bins/1.json
  def destroy
    @bin.destroy
    respond_to do |format|
      format.html { redirect_to bins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bin
      @bin = Bin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bin_params
      params[:bin]
    end
end

app/controllers/certifications_controller.rb
class CertificationsController < ApplicationController
  before_action :set_certification, only: [:show, :edit, :update, :destroy]

  # GET /certifications
  # GET /certifications.json
  def index
    @certifications = Certification.all
  end

  # GET /certifications/1
  # GET /certifications/1.json
  def show
  end

  # GET /certifications/new
  def new
    @certification = Certification.new
  end

  # GET /certifications/1/edit
  def edit
  end

  # POST /certifications
  # POST /certifications.json
  def create
    @certification = Certification.new(certification_params)

    respond_to do |format|
      if @certification.save
        format.html { redirect_to @certification, notice: 'Certification was successfully created.' }
        format.json { render action: 'show', status: :created, location: @certification }
      else
        format.html { render action: 'new' }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /certifications/1
  # PATCH/PUT /certifications/1.json
  def update
    respond_to do |format|
      if @certification.update(certification_params)
        format.html { redirect_to @certification, notice: 'Certification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @certification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /certifications/1
  # DELETE /certifications/1.json
  def destroy
    @certification.destroy
    respond_to do |format|
      format.html { redirect_to certifications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_certification
      @certification = Certification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def certification_params
      params.require(:certification).permit(:cert_name, :cert_company, :category, :description, :logo_url)
    end
end

app/controllers/concerns/current_bin.rb
module CurrentBin
	extend ActiveSupport::Concern

	private

		def set_bin
			@bin = Bin.find(session[:bin_id])
		rescue ActiveRecord::RecordNotFound
			@bin = Bin.create
			session[:bin_id] = @bin.id
		end
	end
	

app/controllers/library_controller.rb
class LibraryController < ApplicationController
  def index
  	@certifications = Certification.order(:cert_name)
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentBin
  before_action :set_bin, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    certification = Certification.find(params[:certification_id])
    @line_item = @bin.line_items.build(certification: certification)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item.bin, notice: 'Line item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:certification_id, :bin_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bins_helper.rb
module BinsHelper
end

app/helpers/certifications_helper.rb
module CertificationsHelper
end

app/helpers/library_helper.rb
module LibraryHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/bins/_form.html.erb
<%= form_for(@bin) do |f| %>
  <% if @bin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bin.errors.count, "error") %> prohibited this bin from being saved:</h2>

      <ul>
      <% @bin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bins/edit.html.erb
<h1>Editing bin</h1>

<%= render 'form' %>

<%= link_to 'Show', @bin %> |
<%= link_to 'Back', bins_path %>

app/views/bins/index.html.erb
<h1>Listing bins</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bins.each do |bin| %>
      <tr>
        <td><%= link_to 'Show', bin %></td>
        <td><%= link_to 'Edit', edit_bin_path(bin) %></td>
        <td><%= link_to 'Destroy', bin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bin', new_bin_path %>

app/views/bins/new.html.erb
<h1>New bin</h1>

<%= render 'form' %>

<%= link_to 'Back', bins_path %>

app/views/bins/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

  <h2>Your Pragmatic Bin</h2>
  	<ul>
  	  <% @bin.line_items.each do |item| %>
  	  	<li><%= item.certification.cert_name %></li>
  	  <% end %>	
  	</ul>

<%= link_to 'Edit', edit_bin_path(@bin) %> |
<%= link_to 'Back', bins_path %>

app/views/certifications/_form.html.erb
<%= form_for(@certification) do |f| %>
  <% if @certification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@certification.errors.count, "error") %> prohibited this certification from being saved:</h2>

      <ul>
      <% @certification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cert_name %><br>
    <%= f.text_field :cert_name %>
  </div>
  <div class="field">
    <%= f.label :cert_company %><br>
    <%= f.text_field :cert_company %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 10 %>
  </div>
  <div class="field">
    <%= f.label :logo_url %><br>
    <%= f.text_field :logo_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/certifications/edit.html.erb
<h1>Editing certification</h1>

<%= render 'form' %>

<%= link_to 'Show', @certification %> |
<%= link_to 'Back', certifications_path %>

app/views/certifications/index.html.erb
<h1>Listing certifications</h1>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>Certification</th>
      <th>Company</th>
      <th>Category</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @certifications.each do |certification| %>
      <tr>
        <td><img src="<%= certification.logo_url %>" alt="microsoft logo" hieght="40" width="40"></td>
        <td><%= certification.cert_name %></td>
        <td><%= certification.cert_company %></td>
        <td><%= certification.category %></td>
        <td><%= certification.description %></td>
        <td><button class="btn btn-default"><%= link_to 'Show', certification %></button></td>
        <td><button class="btn btn-default"><%= link_to 'Edit', edit_certification_path(certification) %></button></td>
        <td><button class="btn btn-default"><%= link_to 'Destroy', certification, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Certification', new_certification_path %>

app/views/certifications/new.html.erb
<h1>New certification</h1>

<%= render 'form' %>

<%= link_to 'Back', certifications_path %>

app/views/certifications/show.html.erb
<p id="notice"><%= notice %></p>


<div>
  <img src="<%= @certification.logo_url %>" alt="company logo" height="70" width="70">
</div>

<p>
  <strong>Cert name:</strong>
  <%= @certification.cert_name %>
</p>

<p>
  <strong>Cert company:</strong>
  <%= @certification.cert_company %>
</p>

<p>
  <strong>Category:</strong>
  <%= @certification.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @certification.description %>
</p>

<%= link_to 'Edit', edit_certification_path(@certification) %> |
<%= link_to 'Back', certifications_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mark6</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class '<%= controller.controller_name %>'>
	<%= render 'shared/navbar' %>
	<%= yield %>

</body>
</html>

app/views/library/index.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h1>First It. Library Catalog</h1>

<% @certifications.each do |certification| %>
  <div class="entry">
  	<%= image_tag(certification.logo_url) %>
  	<h3><%= certification.cert_name %></h3>
  	<%= sanitize(certification.description) %>
  	<div class="category_line">
  		<span class="category"><%= certification.category %></span>
  		<%= button_to 'Add to Bin', line_items_path(certification_id: certification) %>
  	</div>
  </div>
<% end %>

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :certification_id %><br>
    <%= f.text_field :certification_id %>
  </div>
  <div class="field">
    <%= f.label :bin_id %><br>
    <%= f.text_field :bin_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Certification</th>
      <th>Bin</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.certification %></td>
        <td><%= line_item.bin %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Certification:</strong>
  <%= @line_item.certification %>
</p>

<p>
  <strong>Bin:</strong>
  <%= @line_item.bin %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><b>Brand</b></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <li class="active"><%= link_to "Library", root_path %></li>
        <li>About</li>
        <li>Contact</li>
      </ul>
    </div>
  </div>
</nav>
       